version: "3"
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  sonarnet:
    driver: bridge
