"""add coding_question_id, remove team_id

Revision ID: 1d08d1c452cc
Revises: fc30b3cdf0c7
Create Date: 2026-03-12 12:29:32.992094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d08d1c452cc'
down_revision: Union[str, Sequence[str], None] = 'a455937f2760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('coding_question_id', sa.Integer(), nullable=True))
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'answers', 'codingquestions', ['coding_question_id'], ['id'])
    op.alter_column('codingquestionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'codingquestionpaper' in inspector.get_table_names():
        fks = inspector.get_foreign_keys('codingquestionpaper')
        target_fks_to_drop = []
        for fk in fks:
            if 'team_id' in fk['constrained_columns'] or 'adminUser' in fk['constrained_columns']:
                target_fks_to_drop.append(fk['name'])
        
        for fk_name in target_fks_to_drop:
            op.drop_constraint(fk_name, 'codingquestionpaper', type_='foreignkey')
            
        cols = [c['name'] for c in inspector.get_columns('codingquestionpaper')]
        if 'team_id' in cols:
            op.drop_column('codingquestionpaper', 'team_id')
            
        column_to_use = 'admin_user' if 'admin_user' in cols else 'adminUser'
        
        # Check if FK already exists
        fks_after = inspector.get_foreign_keys('codingquestionpaper')
        if not any(column_to_use in fk['constrained_columns'] for fk in fks_after):
            op.create_foreign_key(None, 'codingquestionpaper', 'user', [column_to_use], ['id'])
            
    op.alter_column('codingquestions', 'title',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'problem_statement',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'examples',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'constraints',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'starter_code',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'difficulty',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    if 'interviewsession' in inspector.get_table_names():
        fk_names = [fk['name'] for fk in inspector.get_foreign_keys('interviewsession')]
        if op.f('interviewsession_paper_id_fkey') in fk_names:
            op.drop_constraint(op.f('interviewsession_paper_id_fkey'), 'interviewsession', type_='foreignkey')
        
        # Check if FK already exists
        fks_after = inspector.get_foreign_keys('interviewsession')
        if not any('paper_id' in fk['constrained_columns'] for fk in fks_after):
            op.create_foreign_key(None, 'interviewsession', 'questionpaper', ['paper_id'], ['id'], ondelete='SET NULL')
            
    if 'team' in inspector.get_table_names():
        team_fks = [fk['name'] for fk in inspector.get_foreign_keys('team')]
        if op.f('team_created_by_fkey') in team_fks:
            op.drop_constraint(op.f('team_created_by_fkey'), 'team', type_='foreignkey')
            
        team_cols = [c['name'] for c in inspector.get_columns('team')]
        if 'created_by' in team_cols:
            op.drop_column('team', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('team_created_by_fkey'), 'team', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'interviewsession', type_='foreignkey')
    op.create_foreign_key(op.f('interviewsession_paper_id_fkey'), 'interviewsession', 'questionpaper', ['paper_id'], ['id'])
    op.alter_column('codingquestions', 'marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('6'),
               existing_nullable=False)
    op.alter_column('codingquestions', 'difficulty',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Medium'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Algorithms'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'starter_code',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'constraints',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'examples',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'problem_statement',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'title',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.add_column('codingquestionpaper', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'codingquestionpaper', type_='foreignkey')
    op.create_foreign_key(op.f('codingquestionpaper_adminUser_fkey'), 'codingquestionpaper', 'user', ['adminUser'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('codingquestionpaper_team_id_fkey'), 'codingquestionpaper', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('codingquestionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('answers', 'coding_question_id')
    # ### end Alembic commands ###
