"""Add current_question_index and QuestionAttempt table

Revision ID: 253233871ee4
Revises: 45a4d943ff0f
Create Date: 2026-05-04 18:44:40.258559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '253233871ee4'
down_revision: Union[str, Sequence[str], None] = '45a4d943ff0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    if 'questionattempt' not in inspector.get_table_names():
        op.create_table('questionattempt',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=True),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.Column('coding_question_id', sa.Integer(), nullable=True),
        sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=False),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['coding_question_id'], ['codingquestions.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['interviewsession.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    interview_session_columns = {column['name'] for column in inspector.get_columns('interviewsession')}
    if 'current_question_index' not in interview_session_columns:
        op.add_column('interviewsession', sa.Column('current_question_index', sa.Integer(), nullable=False, server_default='0'))

    op.alter_column('interviewsession', 'allow_proctoring',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviewsession', 'allow_proctoring',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.drop_column('interviewsession', 'current_question_index')
    op.drop_table('questionattempt')
    # ### end Alembic commands ###
