"""Add pause timer fields

Revision ID: 27bb3dfb4991
Revises: c536eb85081a
Create Date: 2026-06-18 12:44:29.397419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bb3dfb4991'
down_revision: Union[str, Sequence[str], None] = 'c536eb85081a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewsession', sa.Column('paused_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interviewsession', sa.Column('last_disconnected_at', sa.DateTime(), nullable=True))
    op.add_column('questionattempt', sa.Column('paused_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('questionattempt', sa.Column('last_disconnected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionattempt', 'last_disconnected_at')
    op.drop_column('questionattempt', 'paused_seconds')
    op.drop_column('interviewsession', 'last_disconnected_at')
    op.drop_column('interviewsession', 'paused_seconds')
    # ### end Alembic commands ###
