"""remove termination_reason from interviewsession

Revision ID: 74d2b17f9873
Revises: 07c29e08ea39
Create Date: 2026-03-16 11:37:11.049011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d2b17f9873'
down_revision: Union[str, Sequence[str], None] = '07c29e08ea39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add columns with server defaults for compatibility with existing data
    op.add_column('interviewsession', sa.Column('tab_switch_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interviewsession', sa.Column('tab_switch_timestamp', sa.DateTime(), nullable=True))
    op.add_column('interviewsession', sa.Column('tab_warning_active', sa.Boolean(), nullable=False, server_default='false'))
    
    # Handle termination_reason dropping defensively
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('interviewsession')]
    if 'termination_reason' in columns:
        op.drop_column('interviewsession', 'termination_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviewsession', 'tab_warning_active')
    op.drop_column('interviewsession', 'tab_switch_timestamp')
    op.drop_column('interviewsession', 'tab_switch_count')
    # ### end Alembic commands ###
