"""Add allow_question_navigate to InterviewSession

Revision ID: 8e852ee7be3b
Revises: b00191284125
Create Date: 2026-03-17 12:36:38.451523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e852ee7be3b'
down_revision: Union[str, Sequence[str], None] = 'b00191284125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewsession', sa.Column('allow_question_navigate', sa.Boolean(), nullable=False))
    op.alter_column('interviewsession', 'tab_switch_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interviewsession', 'tab_warning_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'resume_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviewsession', 'tab_warning_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('interviewsession', 'tab_switch_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('interviewsession', 'allow_question_navigate')
    # ### end Alembic commands ###
