"""Add index to access_token

Revision ID: 9f75d29697a2
Revises: 96d275feaaa1
Create Date: 2026-05-15 14:38:34.229425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f75d29697a2'
down_revision: Union[str, Sequence[str], None] = '96d275feaaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes('user')
    index_names = [idx['name'] for idx in indexes]
    if 'ix_user_access_token' not in index_names:
        op.create_index(op.f('ix_user_access_token'), 'user', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes('user')
    index_names = [idx['name'] for idx in indexes]
    if 'ix_user_access_token' in index_names:
        op.drop_index(op.f('ix_user_access_token'), table_name='user')
    # ### end Alembic commands ###

