"""initial_schema_v3_reverted_team

Revision ID: a455937f2760
Revises: 
Create Date: 2026-03-13 10:59:17.747854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a455937f2760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPER_ADMIN', 'CANDIDATE', name='userrole'), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resume_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('face_embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('codingquestionpaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_user', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codingquestionpaper_name'), 'codingquestionpaper', ['name'], unique=False)
    op.create_table('questionpaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_user', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionpaper_name'), 'questionpaper', ['name'], unique=False)
    op.create_table('codingquestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examples', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starter_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['codingquestionpaper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('invite_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('coding_paper_id', sa.Integer(), nullable=True),
    sa.Column('interview_round', sa.Enum('ROUND_1', 'ROUND_2', 'ROUND_3', 'ROUND_4', 'ROUND_5', name='interviewround'), nullable=True),
    sa.Column('schedule_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('max_warnings', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('enrollment_audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('allow_copy_paste', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coding_paper_id'], ['codingquestionpaper.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['questionpaper.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviewsession_access_token'), 'interviewsession', ['access_token'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('response_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['questionpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('result_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('proctoringevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statustimeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'LINK_ACCESSED', 'AUTHENTICATED', 'SELFIE_UPLOADED', 'ENROLLMENT_STARTED', 'ENROLLMENT_COMPLETED', 'INTERVIEW_ACTIVE', 'INTERVIEW_PAUSED', 'INTERVIEW_COMPLETED', 'SUSPENDED', name='candidatestatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('context_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviewsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_result_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('coding_question_id', sa.Integer(), nullable=True),
    sa.Column('candidate_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcribed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coding_question_id'], ['codingquestions.id'], ),
    sa.ForeignKeyConstraint(['interview_result_id'], ['interviewresult.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codinganswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_result_id', sa.Integer(), nullable=True),
    sa.Column('coding_question_id', sa.Integer(), nullable=True),
    sa.Column('candidate_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcribed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coding_question_id'], ['codingquestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_result_id'], ['interviewresult.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codinganswers')
    op.drop_table('answers')
    op.drop_table('statustimeline')
    op.drop_table('sessionquestion')
    op.drop_table('proctoringevent')
    op.drop_table('interviewresult')
    op.drop_table('questions')
    op.drop_index(op.f('ix_interviewsession_access_token'), table_name='interviewsession')
    op.drop_table('interviewsession')
    op.drop_table('codingquestions')
    op.drop_index(op.f('ix_questionpaper_name'), table_name='questionpaper')
    op.drop_table('questionpaper')
    op.drop_index(op.f('ix_codingquestionpaper_name'), table_name='codingquestionpaper')
    op.drop_table('codingquestionpaper')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
