"""sync_models_to_db

Revision ID: c2f677208028
Revises: 8e852ee7be3b
Create Date: 2026-03-20 12:33:36.111122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2f677208028'
down_revision: Union[str, Sequence[str], None] = '8e852ee7be3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codinganswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_result_id', sa.Integer(), nullable=True),
    sa.Column('coding_question_id', sa.Integer(), nullable=True),
    sa.Column('candidate_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcribed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coding_question_id'], ['codingquestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_result_id'], ['interviewresult.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('coding_question_id', sa.Integer(), nullable=True))
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'answers', 'codingquestions', ['coding_question_id'], ['id'])
    op.add_column('codingquestionpaper', sa.Column('admin_user', sa.Integer(), nullable=True))
    op.alter_column('codingquestionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('codingquestionpaper_team_id_fkey'), 'codingquestionpaper', type_='foreignkey')
    op.drop_constraint(op.f('codingquestionpaper_adminUser_fkey'), 'codingquestionpaper', type_='foreignkey')
    op.create_foreign_key(None, 'codingquestionpaper', 'user', ['admin_user'], ['id'])
    op.drop_column('codingquestionpaper', 'team_id')
    op.drop_column('codingquestionpaper', 'adminUser')
    op.alter_column('codingquestions', 'title',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'problem_statement',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'examples',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'constraints',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'starter_code',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'difficulty',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('codingquestions', 'marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('interviewsession', sa.Column('allow_question_navigate', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('interviewsession', sa.Column('tab_switch_count', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('interviewsession', sa.Column('tab_switch_timestamp', sa.DateTime(), nullable=True))
    op.add_column('interviewsession', sa.Column('tab_warning_active', sa.Boolean(), nullable=False, server_default="false"))
    op.drop_constraint(op.f('interviewsession_paper_id_fkey'), 'interviewsession', type_='foreignkey')
    op.create_foreign_key(None, 'interviewsession', 'questionpaper', ['paper_id'], ['id'], ondelete='SET NULL')
    op.add_column('questionpaper', sa.Column('admin_user', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('questionpaper_adminUser_fkey'), 'questionpaper', type_='foreignkey')
    op.create_foreign_key(None, 'questionpaper', 'user', ['admin_user'], ['id'])
    op.drop_column('questionpaper', 'adminUser')
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('team_created_by_fkey'), 'team', type_='foreignkey')
    op.drop_column('team', 'created_by')
    op.add_column('user', sa.Column('resume_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'resume_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'resume_path')
    op.add_column('team', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('team_created_by_fkey'), 'team', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('questions', 'paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('questionpaper', sa.Column('adminUser', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questionpaper', type_='foreignkey')
    op.create_foreign_key(op.f('questionpaper_adminUser_fkey'), 'questionpaper', 'user', ['adminUser'], ['id'])
    op.drop_column('questionpaper', 'admin_user')
    op.drop_constraint(None, 'interviewsession', type_='foreignkey')
    op.create_foreign_key(op.f('interviewsession_paper_id_fkey'), 'interviewsession', 'questionpaper', ['paper_id'], ['id'])
    op.drop_column('interviewsession', 'tab_warning_active')
    op.drop_column('interviewsession', 'tab_switch_timestamp')
    op.drop_column('interviewsession', 'tab_switch_count')
    op.drop_column('interviewsession', 'allow_question_navigate')
    op.alter_column('codingquestions', 'marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('6'),
               existing_nullable=False)
    op.alter_column('codingquestions', 'difficulty',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Medium'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'topic',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Algorithms'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'starter_code',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'constraints',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'examples',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'problem_statement',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('codingquestions', 'title',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.add_column('codingquestionpaper', sa.Column('adminUser', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('codingquestionpaper', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'codingquestionpaper', type_='foreignkey')
    op.create_foreign_key(op.f('codingquestionpaper_adminUser_fkey'), 'codingquestionpaper', 'user', ['adminUser'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('codingquestionpaper_team_id_fkey'), 'codingquestionpaper', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.alter_column('codingquestionpaper', 'total_marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('codingquestionpaper', 'description',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_column('codingquestionpaper', 'admin_user')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('answers', 'coding_question_id')
    op.drop_table('codinganswers')
    # ### end Alembic commands ###
