"""Add created_by_id to User and SUSPENDED to InterviewStatus

Revision ID: c536eb85081a
Revises: c3b5a106c92b
Create Date: 2026-06-11 16:55:31.094069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c536eb85081a'
down_revision: Union[str, Sequence[str], None] = 'c3b5a106c92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'created_by_id')
    # ### end Alembic commands ###
