"""Add status and timestamps to QuestionAttempt

Revision ID: cab5ecf493c0
Revises: 253233871ee4
Create Date: 2026-05-05 15:37:18.239629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab5ecf493c0'
down_revision: Union[str, Sequence[str], None] = '253233871ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviewsession', 'current_question_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('questionattempt', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('questionattempt', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('questionattempt', sa.Column('expired_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionattempt', 'expired_at')
    op.drop_column('questionattempt', 'submitted_at')
    op.drop_column('questionattempt', 'status')
    op.alter_column('interviewsession', 'current_question_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
