"""increase_blood_group_length

Revision ID: d948deaad21a
Revises: 9f75d29697a2
Create Date: 2026-05-15 16:35:13.526420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd948deaad21a'
down_revision: Union[str, Sequence[str], None] = '9f75d29697a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userdetail', 'blood_group',
               existing_type=sa.VARCHAR(length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userdetail', 'blood_group',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
