"""add resume_path and resume_filename to user remove resume_text

Revision ID: db5a6730bf74
Revises: 07c29e08ea39
Create Date: 2026-03-16 13:06:03.429646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db5a6730bf74'
down_revision: Union[str, Sequence[str], None] = '07c29e08ea39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'interviewsession', 'questionpaper', ['paper_id'], ['id'], ondelete='SET NULL')
    # op.create_foreign_key(None, 'questionpaper', 'user', ['admin_user'], ['id'])
    op.add_column('user', sa.Column('resume_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('resume_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'resume_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'resume_filename')
    op.drop_column('user', 'resume_path')
    # op.drop_constraint(None, 'questionpaper', type_='foreignkey')
    # op.drop_constraint(None, 'interviewsession', type_='foreignkey')
    # ### end Alembic commands ###
