"""Add captured_images to InterviewResult

Revision ID: f89aa036b373
Revises: 27bb3dfb4991
Create Date: 2026-06-18 17:39:58.559150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89aa036b373'
down_revision: Union[str, Sequence[str], None] = '27bb3dfb4991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewresult', sa.Column('captured_images', sa.JSON(), nullable=True))
    op.alter_column('interviewsession', 'paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questionattempt', 'paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionattempt', 'paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('interviewsession', 'paused_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('interviewresult', 'captured_images')
    # ### end Alembic commands ###
